# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BrIM16TdX4rA8PsnOWhEtNI-2tFjBxwk
"""

import numpy as np
def force_vec(s,t,n,o):
  z = np.column_stack([s,t,n,o])
  return z

s1 = np.array([0, 1, 0])
t1 = np.array([0, 0, 1])
n1 = np.array([1, 0, 0])
o1 = np.array([0, 0, 0])
z1=  force_vec(s1,t1,n1,o1)


s2 = np.array([0, 1, 0])
t2 = np.array([0, 0, -1])
n2 = np.array([-1, 0, 0])
o2 = np.array([0, 0, 0])
z2=  force_vec(s2,t2,n2,o2)


#define function to calculate cross product
def cross_prod(x,s):
    A = [x[1]*s[2] - x[2]*x[1],
            x[2]*s[0] - x[0]*s[2],
            x[0]*s[1] - x[1]*s[0]]
    p = np.transpose(A)
    return p
def cross_prod(x,t):
    A = [x[1]*t[2] - x[2]*t[1],
            x[2]*t[0] - x[0]*t[2],
            x[0]*t[1] - x[1]*t[0]]
    q = np.transpose(A)
    return q
def cross_prod(x,n):
    A = [x[1]*n[2] - x[2]*n[1],
            x[2]*n[0] - x[0]*n[2],
            x[0]*n[1] - x[1]*n[0]]
    r = np.transpose(A)
    return r

# test
s1 = np.array([0, 1, 0])
t1 = np.array([0, 0, 1])
n1 = np.array([1, 0, 0])
x1 = np.array([-2, 0, 0])
p1 = cross_prod(x1,s1)
q1 = cross_prod(x1,t1)
r1 = cross_prod(x1,n1)
tau1 = np.array([1, 0, 0])
k= np.column_stack([p1,q1,r1,tau1])
G1 = np.concatenate([z1,k])

s2 = np.array([0, 1, 0])
t2 = np.array([0, 0, -1])
n2 = np.array([-1, 0, 0])
x2 = np.array([2, 0, 0])
p2 = cross_prod(x2,s2)
q2 = cross_prod(x2,t2)
r2 = cross_prod(x2,n2)
tau2 = np.array([-1, 0, 0])
l= np.column_stack([p2,q2,r2,tau2])

G2 = np.concatenate([z2,l])
G= np.block([G1,G2])
print(G)

