# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuOdwUCz2uDLJZxEGL-OyL5DmvnVkIY4
"""

import numpy as np

def generate_candidate_contact_points_2d(length, width):
    # Define corners of the rectangle
    corners = [
        (0, 0),         # Bottom-left corner
        (length, 0),    # Bottom-right corner
        (0, width),     # Top-left corner
        (length, width) # Top-right corner
    ]

    # Define midpoints of the edges
    edges_midpoints = [
        (length / 2, 0),      # Midpoint of bottom edge
        (length / 2, width),  # Midpoint of top edge
        (0, width / 2),       # Midpoint of left edge
        (length, width / 2)   # Midpoint of right edge
    ]

    # Combine corners and edges midpoints
    candidate_points = corners + edges_midpoints

    return candidate_points

# Example dimensions of the 2D rectangle
length = 10
width = 5

candidate_points_2d = generate_candidate_contact_points_2d(length, width)
print("Candidate Contact Points (2D):")
for point in candidate_points_2d:
    print(point)





