# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C7UDw5opnko3-PysV1IQxxekVIbhKyeS
"""

import cv2

# Read the RGB image
rgb_image = cv2.imread(r"C:\Users\anamu\Downloads\MT4J3_AV1.jpeg")

# Convert the RGB image to grayscale
gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)

# Display the grayscale image
cv2.imshow("Grayscale Image", gray_image)

# Wait for a key press and close the window
cv2.waitKey(0)
cv2.destroyAllWindows()