# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118MUORJqg21qia2r4YH5eM1S-Ji_1diQ
"""

import numpy as np

# Define the grasp matrix G
G = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, -1, 1],
    [0, 0, -1, 1, 0, 0],
    [0, 1, 0, -1, 0, 0]
])

# Perform Singular Value Decomposition
U, S, Vt = np.linalg.svd(G)

# Output the results
print("Singular Values (Diagonal of Sigma):")
print(S)